### PR TITLE
Missing configs

### PR DESCRIPTION
**Pull request by DatDraggy**
Had config file of updater, fixed missing configs

### CODE REVIEW

**Comment by DatDraggy** [comment]
Oh, what is $config['TopChannel'] for?

**Comment by DatDraggy** [comment]
Found it out. Added to pull

**Comment by DatDraggy** [comment]
I'm a little stupid. Just realized that I tried to use values from the config in a function... Will fix in a few

**Comment by Kleberstoff** [comment]
Looks good to me, I gonna merge it when I get Home. Thanks again Kieran!

**Comment by Kleberstoff** [comment]
Again, changes seem fine to me, going to merge them now. @DatDraggy I gonna Invite you as Repository Administrator if you don't mind.

**Comment by DatDraggy** [comment]
Oh cool yea thats fine

**Pull request merged**
